# Generated by Django 3.2.19 on 2023-07-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_alter_purchase_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('joindate', models.DateTimeField()),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('emp_number', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('blood', models.CharField(max_length=10)),
                ('parent', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('Phone', models.IntegerField()),
                ('email', models.EmailField(max_length=255, null=True)),
                ('ITN', models.IntegerField(null=True)),
                ('Aadhar', models.IntegerField(null=True)),
                ('UAN', models.IntegerField(null=True)),
                ('PFN', models.IntegerField(null=True)),
                ('PRAN', models.IntegerField(null=True)),
            ],
        ),
    ]
