# Generated by Django 3.2.19 on 2023-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='salary_type',
            field=models.CharField(default='Fixed', max_length=100),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='joindate',
            field=models.DateField(),
        ),
    ]
