# Generated by Django 3.2.19 on 2023-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_auto_20230725_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(default='Active', max_length=200),
        ),
    ]
