# Generated by Django 3.2.19 on 2023-07-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_payroll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='attachment',
            field=models.FileField(default='', null=True, upload_to='doc/'),
        ),
    ]
