# Generated by Django 3.2.19 on 2023-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_auto_20230728_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='TDS',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
