# Generated by Django 3.2.19 on 2023-07-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='cpmment',
            new_name='comment',
        ),
    ]
