# Generated by Django 3.2.19 on 2023-08-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_auto_20230802_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='emp_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
