# Generated by Django 4.2 on 2023-08-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_transportation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=50)),
                ('transsub', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=100)),
                ('cgst_trt_inp', models.CharField(max_length=100)),
                ('cgstin_inp', models.CharField(max_length=100)),
                ('invoiceno', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('trans', models.CharField(max_length=100)),
                ('adda', models.TextField()),
                ('addb', models.TextField()),
                ('srcofsupply', models.CharField(max_length=100)),
                ('transportation', models.CharField(max_length=100)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EWayBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eway_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.ewaybill')),
            ],
        ),
    ]
