# Generated by Django 4.2 on 2023-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_ewaybill_ewaybillitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybill',
            name='cemail',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
