# Generated by Django 4.2 on 2023-08-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_ewaybill_cemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybill',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer'),
        ),
    ]
