# Generated by Django 4.2 on 2023-08-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0021_ewaybill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybill',
            name='adj',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='igst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='note',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='sgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='adda',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='addb',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='cgst_trt_inp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='cgstin_inp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='doc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='invoiceno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='srcofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='trans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='transportation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='transsub',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybill',
            name='vno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybillitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybillitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybillitem',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybillitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybillitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ewaybillitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
