# Generated by Django 4.2.4 on 2023-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0022_ewaybill_adj_ewaybill_cgst_ewaybill_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewaybill',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
