# Generated by Django 4.2.4 on 2023-09-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0024_rename_customer_ewaybill_customerzz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ewaybill',
            old_name='comments',
            new_name='comment',
        ),
    ]
