# Generated by Django 4.2.4 on 2023-09-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_rename_comments_ewaybill_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='GSTIN',
            new_name='gstin',
        ),
    ]
