# Generated by Django 4.2.4 on 2023-09-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_rename_gstin_customer_gstin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='gstin',
            new_name='GSTIN',
        ),
    ]
